version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12.1
    working_directory: /go/src/github.com/vmware/wavefront-adapter-for-istio/
    steps:
      - checkout
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: |
          gometalinter            \
          --vendor                \
          --disable-all           \
          --enable=goimports      \
          --enable=misspell ./...
  build:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/vmware/wavefront-adapter-for-istio/
    steps:
      - checkout
      - run: go build -v ./...
  test:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/vmware/wavefront-adapter-for-istio/
    steps:
      - checkout
      - run: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
      - test
